#!/bin/bash
apt-get update
puppet resource package git ensure=present
mkdir -p /tmp/22053123;
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/22053123/clone ensure=absent force=true
puppet resource file /tmp/22053123/clone ensure=directory
cd /tmp/22053123/clone
git clone https://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@github.com/daemianKoh/22053123_repo.git
mv /tmp/22053123/clone/22053123_repo/22053123_index.html /var/www/html/index.html
